featured_categories:
  type: list
  list_type: category
  default: ""
frame_border_radius:
  type: string
  default: "50%"
frame_bg_color:
  type: string
  default: "var(--primary-low)"
logo_height:
  type: string
  default: "70px"
logo_width:
  type: string
  default: "105px"
speed:
  type: string
  default: "80s"
gap:
  type: string
  default: "10px"